package org.vfeeg.eegfaktura.billing.scenario;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.springframework.core.io.ClassPathResource;
import org.vfeeg.eegfaktura.billing.domain.BillingDocumentItem;
import org.vfeeg.eegfaktura.billing.domain.BillingDocumentType;
import org.vfeeg.eegfaktura.billing.model.Allocation;
import org.vfeeg.eegfaktura.billing.model.BillingDocumentDTO;
import org.vfeeg.eegfaktura.billing.model.DoBillingParams;
import org.vfeeg.eegfaktura.billing.model.DoBillingResults;
import org.vfeeg.eegfaktura.billing.support.BillingRunFixture;
import org.vfeeg.eegfaktura.billing.support.BillingScenarioBase;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Stream;
import java.util.stream.StreamSupport;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.comparesEqualTo;
import static org.hamcrest.Matchers.containsString;
import static org.hamcrest.Matchers.everyItem;
import static org.hamcrest.Matchers.greaterThan;
import static org.hamcrest.Matchers.hasSize;
import static org.hamcrest.Matchers.is;

/**
 * Optional M3 item 1 (B-16): billing on the eegfaktura-v3 world instead of hand-built rows.
 *
 * <p>{@code v3world/} is a committed snapshot (see its README): per community the rows of the real legacy view
 * {@code base.billing_masterdata} and the allocations of one settlement period as the legacy web builds them
 * from the energystore's report — energy generated by v3's {@code energy-mock}, ingested over MQTT by the legacy
 * energystore. Twelve communities: v3's demo world and the workspace's variety communities (quarterly, half-yearly,
 * free kWh, no VAT, metering point fee, producer VAT, three price versions, VAT 10 %, discount). The generator
 * never runs here; the snapshot is refreshed by hand.
 *
 * <p>The expected energy lines are recomputed from the snapshot with the arithmetic of the concept (v3's
 * {@code BillingRules}: amount = allocation (2 places) − free kWh, net = amount × ct / 100 − discount, VAT on
 * the net, all {@code HALF_UP}); the documents are checked for internal consistency.
 */
class BillingV3WorldTests extends BillingScenarioBase {

    private static final LocalDate DOCUMENT_DATE = LocalDate.of(2026, 10, 5);
    private static final JsonNode MASTERDATA = read("v3world/masterdata.json");
    private static final JsonNode ALLOCATIONS = read("v3world/allocations.json");

    static Stream<Arguments> communities() {
        List<Arguments> all = new ArrayList<>();
        ALLOCATIONS.fieldNames().forEachRemaining(code ->
                all.add(Arguments.of(code, ALLOCATIONS.get(code).get("variant").asText())));
        return all.stream();
    }

    @ParameterizedTest(name = "{0} ({1})")
    @MethodSource("communities")
    void previewBillsEveryAllocationWithTheConceptArithmetic(String code, String variant) {
        DoBillingResults results = bill(code, true);

        assertThat(results.getAbstractText(), is(RESULT_PREVIEW_OK));
        List<BillingDocumentDTO> docs = documents(results.getBillingRunId());
        assertThat("documents", docs.size(), greaterThan(0));
        Map<String, BillingDocumentItem> energy = new HashMap<>();
        for (BillingDocumentDTO doc : docs) {
            List<BillingDocumentItem> items = items(doc.getId());
            assertDocumentAddsUp(doc, items);
            items.stream().filter(i -> i.getMeteringPointId() != null && i.getPpuUnit() == null) // custom items have "€"
                    .forEach(i -> assertThat("one energy line per meter", energy.put(i.getMeteringPointId(), i) == null, is(true)));
        }
        for (JsonNode allocation : ALLOCATIONS.get(code).get("allocations")) {
            JsonNode row = row(code, allocation.get("meteringPoint").asText());
            Expected expected = Expected.of(row, allocation.get("allocationKWh").decimalValue());
            BillingDocumentItem item = energy.get(allocation.get("meteringPoint").asText());
            if (expected.gross().signum() == 0) {
                assertThat("no zero line for " + allocation, item == null, is(true));
                continue;
            }
            assertThat("energy line for " + allocation, item != null, is(true));
            assertItem(item, expected.amount().toPlainString(), expected.net().toPlainString(),
                    row.path("tariff_vat_in_percent").asText("0"), expected.vat().toPlainString(),
                    expected.gross().toPlainString());
        }
    }

    /** No VAT anywhere in the small-business community (useVat false on every tariff). */
    @Test
    void smallBusinessCommunityBillsWithoutVat() {
        List<BillingDocumentDTO> docs = documents(bill(code("no-vat"), true).getBillingRunId());

        List<BigDecimal> vat = docs.stream().flatMap(d -> items(d.getId()).stream())
                .map(BillingDocumentItem::getVatValueInEuro).toList();
        assertThat(vat, everyItem(comparesEqualTo(BigDecimal.ZERO)));
        docs.forEach(d -> assertThat(d.getGrossAmountInEuro(), comparesEqualTo(d.getNetAmountInEuro())));
    }

    /** Free kWh (50 per meter and period): a consumer above it gets the deduction text, one below gets no line. */
    @Test
    void freeKwhCommunityDeductsAndExplains() {
        List<BillingDocumentItem> items = documents(bill(code("free-kwh"), true).getBillingRunId()).stream()
                .flatMap(d -> items(d.getId()).stream()).toList();

        assertThat(items.stream().filter(i -> i.getText().contains("abzgl. freie kWh (50,00 kWh)")).count(), greaterThan(0L));
    }

    /** Metering point fee on every consumer and producer meter that is billed. */
    @Test
    void meterFeeCommunityChargesEveryBilledMeter() {
        String code = code("meter-fee");
        List<BillingDocumentItem> items = documents(bill(code, true).getBillingRunId()).stream()
                .filter(d -> d.getBillingDocumentType() == BillingDocumentType.INVOICE)
                .flatMap(d -> items(d.getId()).stream()).toList();

        List<BillingDocumentItem> fees = items.stream().filter(i -> i.getText().startsWith("Zählpunktgebühr")).toList();
        assertThat(fees.size(), greaterThan(0));
        fees.forEach(f -> assertItem(f, "1", "1.50", "20", "0.30", "1.80"));
    }

    /** A final run over a whole community: gapless invoice numbers from the configured start, unique per tenant. */
    @Test
    void finalRunNumbersInvoicesWithoutGaps() {
        String code = code("fees");
        List<BillingDocumentDTO> invoices = documents(bill(code, false).getBillingRunId()).stream()
                .filter(d -> d.getBillingDocumentType() == BillingDocumentType.INVOICE).toList();

        List<String> numbers = invoices.stream().map(BillingDocumentDTO::getDocumentNumber).sorted().toList();
        List<String> expected = new ArrayList<>();
        for (int i = 0; i < numbers.size(); i++) {
            expected.add("TRECH2026%05d".formatted(42 + i));
        }
        assertThat(numbers, is(expected));
        assertThat(numbers, hasSize(invoices.size()));
    }

    /** Mail-relevant data survives the view: every document has the participant's address and e-mail. */
    @Test
    void documentsCarryTheRecipientOfTheView() {
        String code = code("v3-demo");
        List<BillingDocumentDTO> docs = documents(bill(code, true).getBillingRunId());

        docs.forEach(d -> {
            assertThat(d.getRecipientEmail(), containsString("@"));
            assertThat(d.getRecipientParticipantNumber(), containsString("-"));
        });
    }

    // ---- helpers ---------------------------------------------------------------------------------

    private DoBillingResults bill(String code, boolean preview) {
        tenant = code; // cleanUp() deletes this community's rows afterwards
        jdbc.update("delete from base.billing_masterdata where tenant_id = ?", code);
        for (JsonNode row : MASTERDATA.get(code)) {
            jdbc.update("insert into base.billing_masterdata"
                    + " select * from json_populate_record(null::base.billing_masterdata, ?::json)", row.toString());
        }
        BillingRunFixture.forTenant(code).createConfig(billingConfigService, fileDataRepository, true);
        JsonNode period = ALLOCATIONS.get(code);
        DoBillingParams params = new DoBillingParams();
        params.setTenantId(code);
        params.setClearingPeriodType(period.get("clearingPeriodType").asText());
        params.setClearingPeriodIdentifier(period.get("clearingPeriodIdentifier").asText());
        params.setPreview(preview);
        params.setClearingDocumentDate(DOCUMENT_DATE);
        params.setAllocations(StreamSupport.stream(period.get("allocations").spliterator(), false).map(a -> {
            Allocation allocation = new Allocation();
            allocation.setParticipantId(a.get("participantId").asText());
            allocation.setMeteringPoint(a.get("meteringPoint").asText());
            allocation.setAllocationKWh(a.get("allocationKWh").decimalValue());
            return allocation;
        }).toArray(Allocation[]::new));
        return billingService.doBilling(params);
    }

    private static String code(String variant) {
        return communities().map(a -> a.get()).filter(a -> a[1].equals(variant)).map(a -> (String) a[0])
                .findFirst().orElseThrow();
    }

    private static JsonNode row(String code, String meteringPoint) {
        for (JsonNode row : MASTERDATA.get(code)) {
            if (row.get("metering_point_id").asText().equals(meteringPoint)) {
                return row;
            }
        }
        throw new AssertionError("no master row for " + meteringPoint);
    }

    /** Net = Σ item net, gross = Σ item gross = net + VAT sums, every item gross = net + VAT. */
    private static void assertDocumentAddsUp(BillingDocumentDTO doc, List<BillingDocumentItem> items) {
        BigDecimal net = BigDecimal.ZERO;
        BigDecimal gross = BigDecimal.ZERO;
        for (BillingDocumentItem item : items) {
            assertThat("gross of " + item.getText(), item.getGrossValue(),
                    comparesEqualTo(item.getNetValue().add(item.getVatValueInEuro())));
            net = net.add(item.getNetValue());
            gross = gross.add(item.getGrossValue());
        }
        BigDecimal vat = zero(doc.getVat1SumInEuro()).add(zero(doc.getVat2SumInEuro()));
        assertThat("net of " + doc.getRecipientName(), doc.getNetAmountInEuro(), comparesEqualTo(net));
        assertThat("gross of " + doc.getRecipientName(), doc.getGrossAmountInEuro(), comparesEqualTo(gross));
        assertThat("net + VAT of " + doc.getRecipientName(), doc.getGrossAmountInEuro(), comparesEqualTo(net.add(vat)));
    }

    private static BigDecimal zero(BigDecimal value) {
        return value == null ? BigDecimal.ZERO : value;
    }

    private static JsonNode read(String resource) {
        try (InputStream in = new ClassPathResource(resource).getInputStream()) {
            return new ObjectMapper().readTree(in);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    /** The concept's energy line, recomputed from the snapshot row (not from billing's code path). */
    private record Expected(BigDecimal amount, BigDecimal net, BigDecimal vat, BigDecimal gross) {

        static Expected of(JsonNode row, BigDecimal allocation) {
            boolean consumer = "1".equals(row.get("metering_point_type").asText());
            BigDecimal amount = allocation.setScale(2, RoundingMode.HALF_UP);
            if (consumer) {
                amount = amount.subtract(decimal(row, "tariff_freekwh")).max(BigDecimal.ZERO).setScale(2, RoundingMode.HALF_UP);
            }
            BigDecimal cent = decimal(row, consumer ? "tariff_working_fee_per_consumedkwh" : "tariff_credit_amount_per_producedkwh");
            BigDecimal net = amount.multiply(cent).divide(BigDecimal.valueOf(100)).setScale(2, RoundingMode.HALF_UP);
            BigDecimal discount = net.multiply(decimal(row, "tariff_discount")).divide(BigDecimal.valueOf(100))
                    .setScale(2, RoundingMode.HALF_UP);
            net = net.subtract(discount);
            BigDecimal vat = row.path("tariff_use_vat").asBoolean()
                    ? net.multiply(decimal(row, "tariff_vat_in_percent")).divide(BigDecimal.valueOf(100)).setScale(2, RoundingMode.HALF_UP)
                    : BigDecimal.ZERO.setScale(2);
            return new Expected(amount, net, vat, net.add(vat));
        }

        private static BigDecimal decimal(JsonNode row, String column) {
            JsonNode value = row.get(column);
            return value == null || value.isNull() ? BigDecimal.ZERO : value.decimalValue();
        }
    }
}
