create schema if not exists base;

create table if not exists base.billing_masterdata
(
    participant_id                        varchar,
    participant_title_before              varchar,
    participant_firstname                 varchar,
    participant_lastname                  varchar,
    participant_title_after               varchar,
    participant_vat_id                    varchar,
    participant_tax_id                    varchar,
    participant_company_register_number   varchar,
    participant_email                     varchar,
    participant_number                    varchar,
    participant_bank_name                 varchar,
    participant_bank_iban                 varchar,
    participant_bank_owner                varchar,
    participant_sepa_mandate_reference    varchar,
    participant_sepa_mandate_issue_date   varchar,
    participant_sepa_direct_debit         varchar default 'NONE',
    metering_point_id                     varchar,
    equipment_number                      varchar,
    metering_equipment_name               varchar,
    metering_point_type                   varchar,
    tenant_id                             varchar,
    eec_id                                varchar,
    eec_name                              varchar,
    eec_vat_id                            varchar,
    eec_tax_id                            varchar,
    eec_company_register_number           varchar,
    eec_email                             varchar,
    eec_phone                             varchar,
    eec_subject_to_vat                    boolean,
    eec_street                            varchar,
    eec_zip_code                          varchar,
    eec_city                              varchar,
    eec_bank_name                         varchar,
    eec_bank_iban                         varchar,
    eec_bank_owner                        varchar,
    eec_bank_creditor_id                  varchar default 'AT12ZZZ12345678901',
    participant_street                    varchar,
    participant_zip_code                  varchar,
    participant_city                      varchar,
    tariff_type                           varchar,
    tariff_name                           varchar,
    tariff_text                           varchar,
    tariff_id                             varchar,
    tariff_version                        integer,
    tariff_billing_period                 varchar,
    tariff_use_vat                        boolean,
    tariff_vat_in_percent                 numeric,
    tariff_participant_fee                numeric,
    tariff_participant_fee_name           varchar,
    tariff_participant_fee_text           varchar,
    tariff_participant_fee_use_vat        boolean,
    tariff_participant_fee_vat_in_percent numeric,
    tariff_participant_fee_discount       numeric,
    tariff_basic_fee                      numeric,
    tariff_discount                       numeric,
    tariff_working_fee_per_consumedkwh    numeric,
    tariff_credit_amount_per_producedkwh  numeric,
    tariff_freekwh                        numeric,
    tariff_metering_point_fee             numeric,
    tariff_metering_point_fee_text        varchar,
    tariff_metering_point_vat             numeric,
    tariff_use_metering_point_fee         boolean default false
);
